version: '2'
services:
    callme-app:
        image: callme
        external_links:
            - callme-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/callme
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    callme-postgresql:
        extends:
            file: postgresql.yml
            service: callme-postgresql
